baseURL = "https://networknoob.net"
theme = "hermit-v2"
languageCode = "en-us"
title = "Networknoob"


[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]


[params.author]
  about = "Network, automation, infosec, coding."

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  description = "A journey to networking expertise…one noobie step at a time."
  # images = [""]
  themeColor = "#494f5c"

  footerCopyright = "Adam Fitzgerald"
  justifyContent = false
  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  readTime = true
  legacyLayout = false
  shareSocial = true

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/adamfitz"

  [[params.socialLinks]]
    name = "email"
    url = "mailto:adam@networknoob.net"

  [[params.socialLinks]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/adam-fitzgerald-89247445/"

  [[params.socialLinks]]
    name = "rss"
    url = "https://www.networknoob.net/index.xml"


[menu]

[[menu.main]]
    name = "About"
    url = "page/about"
    weight = 10

  [[menu.main]]
    name = "Blogs"
    url = "post/"
    weight = 20
  
  [[menu.main]]
    name = "Projects"
    url = "projects"
    weight = 30

  [[menu.main]]
    name = "Contact"
    url = "page/contact"
    weight = 40

  [[menu.main]]
    name = "tags"
    url = "tags"
    weight = 50