baseurl = "/"
title = "networknoob"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Networknoob"
    description = "a journey to networking expertise…one noob step at a time"
    github = "https://github.com/adamfitz"
    twitter = "https://twitter.com/XXX"
    email = "adam@networknoob.net"
    opengraph = true
    shareTwitter = false
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
