baseurl = "http://172.16.17.202/"
title = "Networknoob"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Adam Fitzgerald"
disqusShortname = "Fitzi"
googleAnalytics = "XXX"
pygmentsUseClasses = true
pygmentsCodefences = true

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
tabWidth = 2

[privacy.disqus]
disable = true

[privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = false

[author]
name = "Adam Fitzgerald"
profile = ""

[taxonomies]
tag = "tags"

[params]
mainSections = [ "post" ]
intro = true
headline = "Networknoob"
description = "a journey to networking expertise…one noobie step at a time"
github = "https://github.com/adamfitz"
linkedin = "https://www.linkedin.com/in/adam-fitzgerald-89247445/"
email = "adam@networknoob.net"
opengraph = true
rss = false
shareTwitter = false
shareGitlab = false
shareFacebook = false
shareLinkedIn = false
shareStackoverflow = false
dateFormat = "Mon, Jan 2, 2006"
exponeaJsUrl = ""
exponeaTarget = ""
exponeaToken = ""
exponeaTrackVisits = false
readingTime = true
readingTimeText = "Estimated reading time:"
fathomUrl = ""
fathomSiteId = ""

  [params.plausibleAnalytics]
  domain = ""
  serverURL = ""

[permalinks]
post = "/:year/:month/:day/:filename/"

[[menu.main]]
name = "Blog"
url = "/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 2

[[menu.main]]
name = "Contact"
url = "/page/contact/"
weight = 3

[[menu.main]]
name = "About"
url = "/page/about/"
weight = 4
